export const S = {
  topbar: {
    background: '#F1F1ED',
    padding: '0 28px',
    display: 'flex' as const,
    alignItems: 'center' as const,
    height: 62,
    gap: 12,
    flexShrink: 0,
  },
  pageTitle: {
    fontFamily: "'Newsreader', serif",
    fontStyle: 'italic' as const,
    fontSize: 20,
    fontWeight: 600,
    color: '#2D2D2D',
  },
  topbarRight: {
    marginLeft: 'auto',
    display: 'flex' as const,
    gap: 10,
    alignItems: 'center' as const,
  },
  searchIcon: {
    position: 'absolute' as const,
    left: 12,
    top: '50%',
    transform: 'translateY(-50%)',
    pointerEvents: 'none' as const,
    color: '#8A8A82',
    display: 'flex',
    alignItems: 'center',
  },
  searchInput: {
    background: '#FAF9F4',
    border: '1px solid rgba(45,45,45,0.12)',
    borderRadius: 20,
    padding: '7px 14px 7px 35px',
    fontSize: 13,
    fontFamily: "'Manrope', sans-serif",
    color: '#2D2D2D',
    width: 210,
    outline: 'none',
    transition: 'border-color 0.15s ease, box-shadow 0.15s ease',
  },
  btnPrimary: {
    padding: '8px 18px',
    borderRadius: 8,
    fontSize: 13,
    fontFamily: "'Manrope', sans-serif",
    cursor: 'pointer',
    border: 'none',
    fontWeight: 600,
    background: 'linear-gradient(160deg, #067D55 0%, #006241 100%)',
    color: '#FFFFFF',
    boxShadow: '0 2px 8px rgba(0,98,65,0.25)',
    transition: 'box-shadow 0.15s ease, transform 0.15s ease',
  },
  btnGhost: {
    padding: '8px 16px',
    borderRadius: 8,
    fontSize: 13,
    fontFamily: "'Manrope', sans-serif",
    cursor: 'pointer',
    border: '1px solid rgba(45,45,45,0.15)',
    fontWeight: 500,
    background: 'rgba(255,255,255,0.6)',
    color: '#4B4B4B',
    transition: 'background 0.15s ease',
  },
  filterBar: {
    padding: '0 32px',
    display: 'flex' as const,
    gap: 6,
    alignItems: 'center' as const,
    background: '#F1F1ED',
    height: 46,
    flexShrink: 0,
    overflowX: 'auto' as const,
  },
  filterLabel: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.8px',
    color: '#6B6B6B',
    marginBottom: 8,
  },
  content: {
    padding: '28px 32px',
    flex: 1,
    overflowY: 'auto' as const,
    background: '#FAF9F4',
  },
  bookGrid: {
    display: 'grid' as const,
    gridTemplateColumns: 'repeat(auto-fill,minmax(148px,1fr))',
    gap: 16,
    marginBottom: 36,
  },
};
